# Learning Parameters
NUM_EPISODES=20
TIMESTEPS_PER_EPISODE=100


# CartPole State Variable Limits
CART_POSITION = 4.8
CART_VELOCITY = 5.0
POLE_ANGLE = 0.418
POLE_ANGLE_VELOCITY = 5.0

# CartPole State Variable Resolution
CART_POSITION_RESOLUTION = 0.1
CART_VELOCITY_RESOLUTION = 0.1
POLE_ANGLE_RESOLUTION = 0.005
POLE_ANGLE_VELOCITY_RESOLUTION = 0.1
